FROM alpine
LABEL org.opencontainers.image.authors="joao.trindade@isel.pt"

WORKDIR /root/isel/temp

RUN echo "Hello, LEIC51N!" > greeting.txt



RUN echo "Useless line..."

CMD ["echo", "Hello LEIC51N!"]
